// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SoloProject.InventoryApi.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int Stock { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal Price { get; set; }
}