// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SoloProject.InventoryApi.Models;

public partial class Transaction
{
    [Key]
    public int TransactionId { get; set; }

    public int ProductId { get; set; }

    public bool TransactionType { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Transactions")]
    public virtual Product Product { get; set; }
}